services:
  mongodb:
    image: mongo:latest
    container_name: monday-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    env_file:
      - ./be/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./be/mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:

networks:
  monday-network:
